theme="default"
font="Consolas"


[testing]
font_size=14
font_family="Consolas"
tab_size=4
theme="light"
auto_save=false
auto_closing_pairs=true
auto_closing_delete=true
auto_indent=true
auto_surround=true
cursor_style="line"
word_wrap=false
exclude_dirs=[".git"]
exclude_types=["__pycache__"]
