# This workflow will install Python dependencies, pyinstaller and build executable with a version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: "Biscuit Nightly Builds"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'nightly')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install prerequisites
        run: |
          sudo apt install python3-dev tcl-dev tk-dev fontconfig libfontconfig1 libfontconfig1-dev cmake cmake-data extra-cmake-modules build-essential
          pip install scikit-build

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller biscuit-editor

      - name: Build biscuit
        run: pyinstaller scripts/linux.spec

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "biscuit-nightly-anylinux"
          path: "dist/"

  build-windows:
    runs-on: windows-latest
    if: contains(github.event.head_commit.message, 'nightly')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build biscuit
        run: pyinstaller scripts/windows.spec

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "biscuit-nightly-windows"
          path: "dist/"
